# -*- coding: utf-8 -*-
"""weather_application_streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkC9sE2WFnQvSrw7HN9kCzxaIX4Qj2WQ
"""

import streamlit as st
import requests
from meteostat import Point, Daily
import datetime
import pandas as pd
import matplotlib.pyplot as plt

# Получение текущей температуры с использованием OpenWeatherMap API
def get_current_temperature(city, api_key):
    url = f'http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric'
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()['main']['temp']
    elif response.status_code == 401:
        st.error('Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.')
        st.stop()
    else:
        st.error(f'Unable to get data for city {city}: {response.status_code}')
        st.stop()

# Загрузка исторических данных для указанного города из Meteostat API
def load_historical_weather(city_name, latitude, longitude, years):
    city_point = Point(latitude, longitude)
    end = datetime.datetime.now()
    start = end - datetime.timedelta(days=years*365)
    historical_data = Daily(city_point, start, end)
    historical_data = historical_data.fetch()
    if not historical_data.empty:
        historical_data['Season'] = historical_data.index.to_series().apply(lambda x: (x.month%12 + 3)//3)
        seasonal_mean = historical_data.groupby('Season')['tavg'].mean()
        seasonal_std = historical_data.groupby('Season')['tavg'].std()
        historical_data['Seasonal Mean'] = historical_data['Season'].map(seasonal_mean)
        historical_data['Seasonal Standard Deviation'] = historical_data['Season'].map(seasonal_std)
        historical_data.rename(columns={
            'tavg': 'Average Temperature',
            'tmin': 'Minimum Temperature',
            'tmax': 'Maximum Temperature',
            'prcp': 'Precipitation',
            'snow': 'Snowfall',
            'wdir': 'Wind Direction',
            'wspd': 'Wind Speed',
            'wpgt': 'Wind Gusts',
            'pres': 'Pressure',
            'tsun': 'Sunshine Hours'
        }, inplace=True)
        return historical_data
    else:
        st.error(f'Unable to load historical data for city {city_name}.')
        return None

# Получение координат города с использованием OpenWeatherMap API
def get_city_coordinates(city, api_key):
    url = f'http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        latitude = data['coord']['lat']
        longitude = data['coord']['lon']
        return latitude, longitude
    elif response.status_code == 401:
        st.error('Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.')
        st.stop()
    else:
        st.error(f'Unable to get coordinates for city {city}: {response.status_code}')
        st.stop()

# Проверка и преобразование данных сезона в числовой формат
def transform_season_column(historical_data):
    if 'season' in historical_data.columns:
        season_mapping = {'winter': 1, 'spring': 2, 'summer': 3, 'autumn': 4}
        historical_data['season'] = historical_data['season'].apply(
            lambda x: season_mapping[x] if x in season_mapping else x
        )
    return historical_data

# Streamlit интерфейс
st.title('Weather Application')

# API ключ
api_key = st.text_input('Enter OpenWeatherMap API key', type='password')
if not api_key:
    st.warning('Enter an API key to continue.')
    st.stop()
else:
    url = f'http://api.openweathermap.org/data/2.5/weather?q=Moscow&appid={api_key}&units=metric'
    response = requests.get(url)
    if response.status_code == 401:
        st.error('Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.')
        st.stop()

# Загрузка файла с историческими данными, обработка
uploaded_file = st.file_uploader('Upload historical data file (CSV)')
historical_data = None
city_list = [
    '...', 'Moscow', 'New York', 'London', 'Paris', 'Tokyo', 'Sydney', 'Berlin', 'Beijing', 'Rio de Janeiro',
    'Dubai', 'Los Angeles', 'Singapore', 'Mumbai', 'Cairo', 'Mexico City'
]
city_selection_method = st.radio('Select city input method', ('From list', 'Manually'))
if city_selection_method == 'From list':
    city = st.selectbox('Select a city', city_list)
else:
    city = st.text_input('Enter city name manually')
if city == '...':
    st.warning('Select a city to continue.')
    st.stop()
elif city == '':
    st.warning('Enter city to continue.')
    st.stop()
else:
    if uploaded_file:
        historical_data = pd.read_csv(uploaded_file)
        historical_data = transform_season_column(historical_data)
        historical_data.rename(columns={'temperature': 'Average Temperature'}, inplace=True)
        historical_data = historical_data.sort_values(by=['city', 'timestamp'])
        if city not in historical_data['city'].unique():
            st.error(f'No historical data available for the selected city: {city} in the uploaded *.csv')
            st.stop()
        historical_data = historical_data[historical_data['city'] == city]
        historical_data['rolling_mean'] = historical_data.groupby('city')['Average Temperature'].transform(lambda x: x.rolling(window=30, min_periods=1).mean())
        seasonal_stats = historical_data.groupby(['city', 'season'])['rolling_mean'].agg(['mean', 'std']).reset_index()
        seasonal_stats.rename(columns={'mean': 'Seasonal Mean', 'std': 'Seasonal Standard Deviation'}, inplace=True)
        historical_data = historical_data.merge(seasonal_stats, on=['city', 'season'], how='left', suffixes=('', '_seasonal'))
        historical_data.rename(columns={'season': 'Season'}, inplace=True)
    latitude, longitude = get_city_coordinates(city, api_key)
    if latitude is not None and longitude is not None:
        st.success(f'Coordinates of {city}: latitude {latitude}, longitude {longitude}')
        if historical_data is None:
            years = st.slider('Select the number of years for historical data', min_value=1, max_value=50, value=10, step=1)
            historical_data = load_historical_weather(city, latitude, longitude, years)
        if historical_data is not None:
            if 'timestamp' in historical_data.columns:
                historical_data['timestamp'] = pd.to_datetime(historical_data['timestamp'])
                historical_data.set_index('timestamp', inplace=True)
            st.write('Loaded historical data:')
            st.write(historical_data.sample(10))
            st.write(historical_data.describe())

# Визуализация для данных из API или CSV
            st.subheader('Visualization of Historical Data')
            fig, ax = plt.subplots(figsize=(18, 18))
            ax.plot(historical_data.index, historical_data['Average Temperature'], label='Temperature')

# Добавление сезонов с разными цветами
            season_colors = {1: 'blue', 2: 'yellow', 3: 'red', 4: 'green'}
            seasons = historical_data['Season'].unique()
            for season in seasons:
                season_data = historical_data[historical_data['Season'] == season]
                season_name = {1: 'Winter', 2: 'Spring', 3: 'Summer', 4: 'Autumn'}[season]
                ax.axhline(y=season_data['Seasonal Mean'].iloc[0], color=season_colors.get(season, 'black'), linestyle='--', alpha=0.7, label=f'{season_name} season mean')
                ax.fill_between(
                    season_data.index,
                    season_data['Seasonal Mean'] - 2 * season_data['Seasonal Standard Deviation'],
                    season_data['Seasonal Mean'] + 2 * season_data['Seasonal Standard Deviation'],
                    color=season_colors.get(season, 'black'),
                    alpha=0.2,
                    label=f'{season_name} season range'
                )

# Выделение аномалий
            anomalies = historical_data[(historical_data['Average Temperature'] > historical_data['Seasonal Mean'] + 2 * historical_data['Seasonal Standard Deviation']) |
                                        (historical_data['Average Temperature'] < historical_data['Seasonal Mean'] - 2 * historical_data['Seasonal Standard Deviation'])]
            ax.scatter(anomalies.index, anomalies['Average Temperature'], color='red', label='Anomalies')
            ax.set_title('Historical Temperature Time Series')
            ax.set_xlabel('Date')
            ax.set_ylabel('Temperature (°C)')
            fig.autofmt_xdate()
            ax.legend()
            st.pyplot(fig)

# Получение текущей температуры
if city and historical_data is not None:
    current_temperature = get_current_temperature(city, api_key)
    if current_temperature is not None:
        st.success(f'Current temperature in {city}: {current_temperature}°C')

# Проверка на аномальность
        current_season = (datetime.datetime.now().month % 12 + 3) // 3
        seasonal_mean = historical_data.loc[historical_data['Season'] == current_season, 'Seasonal Mean'].mean()
        seasonal_std = historical_data.loc[historical_data['Season'] == current_season, 'Seasonal Standard Deviation'].mean()
        if abs(current_temperature - seasonal_mean) <= 2 * seasonal_std:
            st.info(f'The temperature {current_temperature}°C is normal for the current season.')
        else:
            st.warning(f'The temperature {current_temperature}°C is abnormal for the current season.')